name: ipy_JSME_SMARTS
channels:
  - conda-forge
  #- default
dependencies:
  - python=3.6
  - biopandas
  - ipython
  - jupyter
  - jupyterlab
  - rdkit==2020.09.3
  - ipywidgets<8
  - traitlets
