name: ipy_JSME_SMARTS-pattern-search
channels:
  - conda-forge
  - default
dependencies:
  - python=3.6
  - biopandas
  - jupyterlab==2.2.9
  - rdkit==2020.09.3
  - ipywidgets==7.5.1
  - traitlets
